### PR TITLE
added the commandline flag to not merge sections.

### PR DESCRIPTION
**Pull request by CR3Swapper**
rdata/data sections clean. Now they should only contain information that my code actually uses. All the import/export/exception/debug data/etc will be in their sections. Want to keep my rdata/data sections clean as a whistle so that when i turn them into data symbols in our obfuscation engine it wont contain all these bytes for imports/exports ETC. just need the code, the data the code uses, and we make our own abstractions of imports.

### CODE REVIEW

**Comment by CR3Swapper** [comment]
this issue is associated with this pr.

https://github.com/backengineering/llvm-msvc/issues/79

**Comment by gmh5225** [comment]
You shoule disable your local clang-format. Otherwise it will affect other unrelated code.
Put your code into the following website, then format it and copy it out.
https://godbolt.org

**Comment by CR3Swapper** [comment]
> You shoule disable your local clang-format. Otherwise it will affect other unrelated code. Put your code into the following website, then format it and copy it out. https://godbolt.org

ok will do.

**Comment by CR3Swapper** [comment]
i fixed the formating mr gmh :)

**Comment by gmh5225** [comment]
Counter-Terrorists win

**Pull request merged**
